
var _ = require('underscore');
var Users = require('./models/users');


module.exports = function (app) {

    var data = [{
        "id": 1,
        "firstname": "Shaun",
        "lastname": "Kennion",
        "email": "skennion0@japanpost.jp"
    }, {
        "id": 2,
        "firstname": "Berky",
        "lastname": "Saddington",
        "email": "bsaddington1@biglobe.ne.jp"
    }, {
        "id": 3,
        "firstname": "Sarah",
        "lastname": "Kivelle",
        "email": "skivelle2@google.de"
    }, {
        "id": 4,
        "firstname": "Dorolice",
        "lastname": "Elwin",
        "email": "delwin3@ebay.com"
    }, {
        "id": 5,
        "firstname": "Valdemar",
        "lastname": "Mecozzi",
        "email": "vmecozzi4@feedburner.com"
    }, {
        "id": 6,
        "firstname": "Larine",
        "lastname": "Golsworthy",
        "email": "lgolsworthy5@berkeley.edu"
    }, {
        "id": 7,
        "firstname": "Graeme",
        "lastname": "Lyptrade",
        "email": "glyptrade6@google.nl"
    }, {
        "id": 8,
        "firstname": "Jermayne",
        "lastname": "Surgey",
        "email": "jsurgey7@washington.edu"
    }, {
        "id": 9,
        "firstname": "Marilyn",
        "lastname": "Peatman",
        "email": "mpeatman8@cpanel.net"
    }, {
        "id": 10,
        "firstname": "Roberto",
        "lastname": "Boddam",
        "email": "rboddam9@chronoengine.com"
    }, {
        "id": 11,
        "firstname": "Pren",
        "lastname": "Denniston",
        "email": "pdennistona@freewebs.com"
    }, {
        "id": 12,
        "firstname": "Titus",
        "lastname": "Newlands",
        "email": "tnewlandsb@biglobe.ne.jp"
    }, {
        "id": 13,
        "firstname": "Kira",
        "lastname": "Broske",
        "email": "kbroskec@soup.io"
    }, {
        "id": 14,
        "firstname": "Luella",
        "lastname": "Pley",
        "email": "lpleyd@businesswire.com"
    }, {
        "id": 15,
        "firstname": "Janaya",
        "lastname": "Wartnaby",
        "email": "jwartnabye@alibaba.com"
    }, {
        "id": 16,
        "firstname": "Barthel",
        "lastname": "Cowton",
        "email": "bcowtonf@walmart.com"
    }, {
        "id": 17,
        "firstname": "Lena",
        "lastname": "Cominello",
        "email": "lcominellog@apple.com"
    }, {
        "id": 18,
        "firstname": "Ranna",
        "lastname": "Rawstorne",
        "email": "rrawstorneh@acquirethisname.com"
    }, {
        "id": 19,
        "firstname": "Evangelina",
        "lastname": "Brimblecomb",
        "email": "ebrimblecombi@youku.com"
    }, {
        "id": 20,
        "firstname": "Ettie",
        "lastname": "Reyna",
        "email": "ereynaj@discovery.com"
    }, {
        "id": 21,
        "firstname": "Emery",
        "lastname": "Drakard",
        "email": "edrakardk@sakura.ne.jp"
    }, {
        "id": 22,
        "firstname": "Lavinie",
        "lastname": "Wildt",
        "email": "lwildtl@hud.gov"
    }, {
        "id": 23,
        "firstname": "Dell",
        "lastname": "Nussey",
        "email": "dnusseym@mlb.com"
    }, {
        "id": 24,
        "firstname": "Agnesse",
        "lastname": "Springtorpe",
        "email": "aspringtorpen@nytimes.com"
    }, {
        "id": 25,
        "firstname": "Beverlie",
        "lastname": "Slowgrave",
        "email": "bslowgraveo@diigo.com"
    }, {
        "id": 26,
        "firstname": "Ardra",
        "lastname": "Zoane",
        "email": "azoanep@abc.net.au"
    }, {
        "id": 27,
        "firstname": "Dulcinea",
        "lastname": "Rittelmeyer",
        "email": "drittelmeyerq@jugem.jp"
    }, {
        "id": 28,
        "firstname": "Johnnie",
        "lastname": "Crawforth",
        "email": "jcrawforthr@cnbc.com"
    }, {
        "id": 29,
        "firstname": "Eartha",
        "lastname": "Hundell",
        "email": "ehundells@de.vu"
    }, {
        "id": 30,
        "firstname": "Nero",
        "lastname": "Vasilischev",
        "email": "nvasilischevt@samsung.com"
    }, {
        "id": 31,
        "firstname": "Thomasina",
        "lastname": "Kinnach",
        "email": "tkinnachu@yandex.ru"
    }, {
        "id": 32,
        "firstname": "Benoite",
        "lastname": "Callcott",
        "email": "bcallcottv@walmart.com"
    }, {
        "id": 33,
        "firstname": "Hyman",
        "lastname": "Zanutti",
        "email": "hzanuttiw@live.com"
    }, {
        "id": 34,
        "firstname": "Carmelita",
        "lastname": "Shugg",
        "email": "cshuggx@studiopress.com"
    }, {
        "id": 35,
        "firstname": "Milt",
        "lastname": "Hiers",
        "email": "mhiersy@marriott.com"
    }, {
        "id": 36,
        "firstname": "Ricoriki",
        "lastname": "Stronack",
        "email": "rstronackz@google.es"
    }, {
        "id": 37,
        "firstname": "Vicki",
        "lastname": "Jelphs",
        "email": "vjelphs10@army.mil"
    }, {
        "id": 38,
        "firstname": "Emmerich",
        "lastname": "Ridgway",
        "email": "eridgway11@liveinternet.ru"
    }, {
        "id": 39,
        "firstname": "Bryce",
        "lastname": "Fundell",
        "email": "bfundell12@digg.com"
    }, {
        "id": 40,
        "firstname": "Abner",
        "lastname": "McCandie",
        "email": "amccandie13@123-reg.co.uk"
    }, {
        "id": 41,
        "firstname": "Bordie",
        "lastname": "Lewing",
        "email": "blewing14@reverbnation.com"
    }, {
        "id": 42,
        "firstname": "Alikee",
        "lastname": "Grattan",
        "email": "agrattan15@github.io"
    }, {
        "id": 43,
        "firstname": "Antonina",
        "lastname": "Burgan",
        "email": "aburgan16@cam.ac.uk"
    }, {
        "id": 44,
        "firstname": "Hadrian",
        "lastname": "Cunniam",
        "email": "hcunniam17@last.fm"
    }, {
        "id": 45,
        "firstname": "Tony",
        "lastname": "Kilby",
        "email": "tkilby18@spotify.com"
    }, {
        "id": 46,
        "firstname": "Chadd",
        "lastname": "Chafney",
        "email": "cchafney19@sitemeter.com"
    }, {
        "id": 47,
        "firstname": "Antonella",
        "lastname": "Balbeck",
        "email": "abalbeck1a@hexun.com"
    }, {
        "id": 48,
        "firstname": "Enrique",
        "lastname": "Biasioli",
        "email": "ebiasioli1b@mtv.com"
    }, {
        "id": 49,
        "firstname": "Jeff",
        "lastname": "Cobon",
        "email": "jcobon1c@independent.co.uk"
    }, {
        "id": 50,
        "firstname": "Guglielma",
        "lastname": "Laughlin",
        "email": "glaughlin1d@cisco.com"
    }, {
        "id": 51,
        "firstname": "Gardie",
        "lastname": "McRoberts",
        "email": "gmcroberts1e@nps.gov"
    }, {
        "id": 52,
        "firstname": "Roger",
        "lastname": "Paiton",
        "email": "rpaiton1f@comcast.net"
    }, {
        "id": 53,
        "firstname": "Konstantin",
        "lastname": "Arangy",
        "email": "karangy1g@studiopress.com"
    }, {
        "id": 54,
        "firstname": "Philippa",
        "lastname": "McMains",
        "email": "pmcmains1h@google.cn"
    }, {
        "id": 55,
        "firstname": "Bridie",
        "lastname": "Ivanuschka",
        "email": "bivanuschka1i@google.com.br"
    }, {
        "id": 56,
        "firstname": "Mitchael",
        "lastname": "Mayward",
        "email": "mmayward1j@mail.ru"
    }, {
        "id": 57,
        "firstname": "Agace",
        "lastname": "Duchart",
        "email": "aduchart1k@com.com"
    }, {
        "id": 58,
        "firstname": "Noella",
        "lastname": "Plesing",
        "email": "nplesing1l@dailymotion.com"
    }, {
        "id": 59,
        "firstname": "Perrine",
        "lastname": "St. John",
        "email": "pstjohn1m@sphinn.com"
    }, {
        "id": 60,
        "firstname": "Jessie",
        "lastname": "Helks",
        "email": "jhelks1n@icq.com"
    }, {
        "id": 61,
        "firstname": "Elias",
        "lastname": "Roderham",
        "email": "eroderham1o@sfgate.com"
    }, {
        "id": 62,
        "firstname": "Karylin",
        "lastname": "Pyford",
        "email": "kpyford1p@shareasale.com"
    }, {
        "id": 63,
        "firstname": "Nerty",
        "lastname": "Kleinbaum",
        "email": "nkleinbaum1q@lycos.com"
    }, {
        "id": 64,
        "firstname": "Fulvia",
        "lastname": "Hogben",
        "email": "fhogben1r@list-manage.com"
    }, {
        "id": 65,
        "firstname": "Izak",
        "lastname": "Goburn",
        "email": "igoburn1s@gnu.org"
    }, {
        "id": 66,
        "firstname": "Anna",
        "lastname": "Kalinowsky",
        "email": "akalinowsky1t@smugmug.com"
    }, {
        "id": 67,
        "firstname": "Pembroke",
        "lastname": "Plampeyn",
        "email": "pplampeyn1u@weather.com"
    }, {
        "id": 68,
        "firstname": "Eda",
        "lastname": "Feechum",
        "email": "efeechum1v@google.fr"
    }, {
        "id": 69,
        "firstname": "Ramon",
        "lastname": "Bonnefin",
        "email": "rbonnefin1w@jigsy.com"
    }, {
        "id": 70,
        "firstname": "Duke",
        "lastname": "Beddard",
        "email": "dbeddard1x@jalbum.net"
    }, {
        "id": 71,
        "firstname": "Charis",
        "lastname": "Pickthorne",
        "email": "cpickthorne1y@amazon.co.uk"
    }, {
        "id": 72,
        "firstname": "Carlos",
        "lastname": "Konneke",
        "email": "ckonneke1z@hubpages.com"
    }, {
        "id": 73,
        "firstname": "Cristiano",
        "lastname": "Rickcord",
        "email": "crickcord20@geocities.jp"
    }, {
        "id": 74,
        "firstname": "Nial",
        "lastname": "Stanlike",
        "email": "nstanlike21@squidoo.com"
    }, {
        "id": 75,
        "firstname": "Wren",
        "lastname": "Klimowski",
        "email": "wklimowski22@cnbc.com"
    }, {
        "id": 76,
        "firstname": "Perl",
        "lastname": "MacGiffin",
        "email": "pmacgiffin23@hostgator.com"
    }, {
        "id": 77,
        "firstname": "Paolo",
        "lastname": "Bewshaw",
        "email": "pbewshaw24@weibo.com"
    }, {
        "id": 78,
        "firstname": "Lorettalorna",
        "lastname": "Banck",
        "email": "lbanck25@amazonaws.com"
    }, {
        "id": 79,
        "firstname": "Tamarra",
        "lastname": "Egar",
        "email": "tegar26@mit.edu"
    }, {
        "id": 80,
        "firstname": "Fee",
        "lastname": "Toke",
        "email": "ftoke27@alibaba.com"
    }, {
        "id": 81,
        "firstname": "Fania",
        "lastname": "Cotman",
        "email": "fcotman28@smugmug.com"
    }, {
        "id": 82,
        "firstname": "Jermaine",
        "lastname": "Feacham",
        "email": "jfeacham29@php.net"
    }, {
        "id": 83,
        "firstname": "Harlie",
        "lastname": "Sandeford",
        "email": "hsandeford2a@nydailynews.com"
    }, {
        "id": 84,
        "firstname": "Haydon",
        "lastname": "Zavattero",
        "email": "hzavattero2b@arstechnica.com"
    }, {
        "id": 85,
        "firstname": "Gordan",
        "lastname": "Piet",
        "email": "gpiet2c@yellowbook.com"
    }, {
        "id": 86,
        "firstname": "Faustina",
        "lastname": "Fegan",
        "email": "ffegan2d@forbes.com"
    }, {
        "id": 87,
        "firstname": "Augustus",
        "lastname": "Liddell",
        "email": "aliddell2e@dot.gov"
    }, {
        "id": 88,
        "firstname": "Charlena",
        "lastname": "McArdle",
        "email": "cmcardle2f@dot.gov"
    }, {
        "id": 89,
        "firstname": "Aguistin",
        "lastname": "Newbigging",
        "email": "anewbigging2g@chronoengine.com"
    }, {
        "id": 90,
        "firstname": "Janella",
        "lastname": "Kernoghan",
        "email": "jkernoghan2h@amazon.de"
    }, {
        "id": 91,
        "firstname": "Merle",
        "lastname": "Jacklings",
        "email": "mjacklings2i@delicious.com"
    }, {
        "id": 92,
        "firstname": "Dorice",
        "lastname": "Willoughey",
        "email": "dwilloughey2j@drupal.org"
    }, {
        "id": 93,
        "firstname": "Oliver",
        "lastname": "Antoinet",
        "email": "oantoinet2k@google.pl"
    }, {
        "id": 94,
        "firstname": "Annnora",
        "lastname": "Vela",
        "email": "avela2l@businessinsider.com"
    }, {
        "id": 95,
        "firstname": "Nickolaus",
        "lastname": "Tomney",
        "email": "ntomney2m@webnode.com"
    }, {
        "id": 96,
        "firstname": "Bar",
        "lastname": "Trazzi",
        "email": "btrazzi2n@reverbnation.com"
    }, {
        "id": 97,
        "firstname": "Adair",
        "lastname": "McBrearty",
        "email": "amcbrearty2o@163.com"
    }, {
        "id": 98,
        "firstname": "Chaddy",
        "lastname": "Folkes",
        "email": "cfolkes2p@free.fr"
    }, {
        "id": 99,
        "firstname": "Hayward",
        "lastname": "Sent",
        "email": "hsent2q@angelfire.com"
    }, {
        "id": 100,
        "firstname": "Ingeborg",
        "lastname": "Slixby",
        "email": "islixby2r@zimbio.com"
    }];

    _.each(data, function(d) {
        Users.create(d, function (err, res) {
            if (!err) console.log("Inserted!");
        });
    });

};
